# Generated by Django 2.2 on 2019-04-24 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetGuruMovieDB', '0003_auto_20190424_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 19, 57, 40, 563425), verbose_name='date published'),
        ),
    ]
